<a href="https://colab.research.google.com/github/junaid0051/data-science-programs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

JUNAID N M

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


1. arithmetic operators

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([3,2,4])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)
print(arr1%arr2)

[4 4 7]
[-2  0 -1]
[ 3  4 12]
[0.33333333 1.         0.75      ]
[ 1  4 81]
[1 0 3]


2. comparison operators


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([3,2,4])
print(arr1>arr2)
print(arr1==arr2)
print(arr1!=arr2)

[False False False]
[False  True False]
[ True False  True]


3. ARRAY SHAPE OPERATIONS


In [ ]:
arr1=np.array([1,2,3])         #1dimentional array
arr2=np.array([[1,2,3],[5,4,6]])             #2dimentional array
arr3=np.array([[[1,2,3],[2,5,8],[7,8,9]]])   #3dimentional array
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


(3,)
(2, 3)
(1, 3, 3)


5 dimentional array

In [ ]:
arr5=np.array([[[[[1,2,3],[2,3,4],[4,5,6],[2,4,8],[4,5,6]]]]])
print(arr5.shape)

(1, 1, 1, 5, 3)
